BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        TextInput:
            id: 'input_number'
            text: ''
            font_size: 48
            multiline: False
        orientation: 'horizontal'
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button: 'Down'
    Button:
        text: 'Convert miles to km'
    Label:
        id: 'output_label'